CREATE TABLE IF NOT EXISTS collector.satel_rtu_cdr
(
    record_id UUID,
    device_id UUID,
    file_id UUID,
    row_number UInt64,
    ingested_at DateTime64(3, 'UTC'),
    parser_version LowCardinality(String),
    template_key LowCardinality(String),
    cdr_id String,
    cdr_date Nullable(DateTime64(3, 'UTC')),
    setup_time Nullable(DateTime64(3, 'UTC')),
    connect_time Nullable(DateTime64(3, 'UTC')),
    disconnect_time Nullable(DateTime64(3, 'UTC')),
    duration_ms Nullable(UInt64),
    elapsed_time Nullable(Float64),
    outcome LowCardinality(String),
    in_ani String,
    in_dnis String,
    out_ani String,
    out_dnis String,
    bill_ani String,
    bill_dnis String,
    src_user String,
    dst_user String,
    radius_user String,
    src_name String,
    dst_name String,
    dp_name String,
    in_cpc LowCardinality(String),
    out_cpc LowCardinality(String),
    in_zone String,
    out_zone String,
    in_orig_dnis String,
    out_orig_dnis String,
    in_ani_type_of_number LowCardinality(String),
    in_dnis_type_of_number LowCardinality(String),
    out_ani_type_of_number LowCardinality(String),
    out_dnis_type_of_number LowCardinality(String),
    in_orig_dnis_type_of_number LowCardinality(String),
    out_orig_dnis_type_of_number LowCardinality(String),
    ext_ani_type_of_number LowCardinality(String),
    ext_dnis_type_of_number LowCardinality(String),
    ext_orig_dnis_type_of_number LowCardinality(String),
    in_ani_screening LowCardinality(String),
    in_ani_presentation LowCardinality(String),
    out_ani_screening LowCardinality(String),
    out_ani_presentation LowCardinality(String),
    in_lrn String,
    retrieved_lrn String,
    lrn String,
    ext_lrn String,
    out_lrn String,
    lnp_server String,
    signal_node_name String,
    src_gatekeeper_address String,
    remote_src_sig_address String,
    remote_dst_sig_address String,
    remote_src_media_address String,
    remote_dst_media_address String,
    local_src_sig_address String,
    local_dst_sig_address String,
    local_src_media_address String,
    local_dst_media_address String,
    in_leg_proto LowCardinality(String),
    out_leg_proto LowCardinality(String),
    in_leg_transport_proto LowCardinality(String),
    out_leg_transport_proto LowCardinality(String),
    conf_id String,
    in_leg_call_id String,
    out_leg_call_id String,
    src_in_leg_conf_id String,
    src_in_leg_call_id String,
    src_out_leg_call_id String,
    in_leg_codecs String,
    out_leg_codecs String,
    disconnect_code UInt64,
    disconnect_text String,
    disconnect_success Bool,
    disconnect_initiator LowCardinality(String),
    src_disconnect_codes String,
    dst_disconnect_codes String,
    src_disconnect_text String,
    dst_disconnect_text String,
    pdd Nullable(Float64),
    scd Nullable(Float64),
    term_elapsed_time Nullable(Float64),
    term_setup_time Nullable(DateTime64(3, 'UTC')),
    term_connect_time Nullable(DateTime64(3, 'UTC')),
    term_disconnect_time Nullable(DateTime64(3, 'UTC')),
    term_pdd Nullable(Float64),
    term_scd Nullable(Float64),
    src_media_bytes_in Nullable(UInt64),
    src_media_bytes_out Nullable(UInt64),
    dst_media_bytes_in Nullable(UInt64),
    dst_media_bytes_out Nullable(UInt64),
    src_media_packets Nullable(UInt64),
    dst_media_packets Nullable(UInt64),
    src_media_packets_late Nullable(UInt64),
    dst_media_packets_late Nullable(UInt64),
    src_media_packets_lost Nullable(UInt64),
    dst_media_packets_lost Nullable(UInt64),
    src_min_jitter Nullable(Float64),
    src_max_jitter Nullable(Float64),
    dst_min_jitter Nullable(Float64),
    dst_max_jitter Nullable(Float64),
    route_retries Nullable(UInt64),
    outgoing_pulses Nullable(UInt64),
    incoming_pulses Nullable(UInt64),
    looping_cycles Nullable(UInt64),
    proxy_mode LowCardinality(String),
    lar_fault_reason String,
    media_group String,
    external_router String,
    radius_group String,
    sip_routing_group String,
    auth_dnis String,
    ext_ani String,
    ext_dnis String,
    ext_sig_address String,
    in_partner_id String,
    out_partner_id String,
    in_encryption LowCardinality(String),
    out_encryption LowCardinality(String),
    record_type LowCardinality(String),
    last_cdr Bool,
    raw_fields Map(String, String),
    source_timezone LowCardinality(String),
    source_utc_offset_minutes Int16,
    timezone_revision UInt64
)
ENGINE = ReplacingMergeTree(ingested_at)
PARTITION BY toYYYYMM(coalesce(setup_time, cdr_date, ingested_at))
ORDER BY (device_id, cdr_id, record_id)
TTL toDateTime(coalesce(setup_time, cdr_date, ingested_at)) + INTERVAL 1095 DAY DELETE;

CREATE TABLE IF NOT EXISTS collector.satel_rtu_cdr_time_facts
(
    device_id UUID,
    timezone_revision UInt64,
    record_id UUID,
    interpreted_at DateTime64(6, 'UTC'),
    cdr_date_utc Nullable(DateTime64(3, 'UTC')),
    setup_time_utc Nullable(DateTime64(3, 'UTC')),
    connect_time_utc Nullable(DateTime64(3, 'UTC')),
    disconnect_time_utc Nullable(DateTime64(3, 'UTC')),
    term_setup_time_utc Nullable(DateTime64(3, 'UTC')),
    term_connect_time_utc Nullable(DateTime64(3, 'UTC')),
    term_disconnect_time_utc Nullable(DateTime64(3, 'UTC')),
    source_timezone LowCardinality(String),
    source_utc_offset_minutes Int16
)
ENGINE = ReplacingMergeTree(interpreted_at)
PARTITION BY toYYYYMM(coalesce(setup_time_utc, cdr_date_utc, interpreted_at))
ORDER BY (device_id, timezone_revision, record_id)
TTL toDateTime(interpreted_at) + INTERVAL 1095 DAY DELETE;
