import { describe, expect, it } from 'vitest'
import main from './main.tsx?raw'
import { deviceSurfaces, fallbackTemplates } from './equipment'

describe('custom antifraud UI cleanup', () => {
  it('removes legacy SyslogDiagnosticPanel fields and banners', () => {
    expect(main).not.toContain('SyslogDiagnosticPanel')
    expect(main).not.toContain('SyslogDiagnostics')
    expect(main).not.toContain('SyslogBreakdown')
    expect(main).not.toContain('parserProjectionStatus')
    expect(main).not.toContain('correlationStatus')
    expect(main).not.toContain('correlationAssignmentLag')
    expect(main).not.toContain('pendingDirtyBuckets')
    expect(main).not.toContain('unknownNoCategoryEvidence')
    expect(main).not.toContain('latestLifecycleAt')
    expect(main).not.toContain('breakdown.map')
    expect(main).not.toContain('Все Syslog')
    expect(main).not.toContain('Нераспознанное')
  })

  it('exposes runtime settings editor in system settings', () => {
    expect(main).toContain('RuntimeSettingsEditor')
    expect(main).toContain("'/system/runtime-settings'")
    expect(main).toContain('Параметры')
    expect(main).toContain('Обогащение CDR (PSTN / GeoIP)')
    expect(main).toContain('enrichmentApis')
    expect(main).toContain('Лимиты контейнеров Docker')
    expect(main).toContain('container-limits.env')
  })

  it('exposes searchable system audit logs grouped by category', () => {
    expect(main).toContain('SystemAuditLogsPanel')
    expect(main).toContain('/system/audit-logs?limit=300')
    expect(main).toContain('>Логи</button>')
    expect(main).toContain('AUDIT_CATEGORY_LABELS')
    expect(main).toContain('Аутентификация')
  })

  it('loads operational diagnostics from the admin endpoint on demand', () => {
    expect(main).toContain('OperationalDiagnosticsPanel')
    expect(main).toContain("'/system/diagnostics'")
    expect(main).toContain('<summary>Диагностика</summary>')
    expect(main).toContain('projectionQueue')
    expect(main).toContain('projectionDevices')
    expect(main).toContain('classificationGap')
    expect(main).toContain('maxDeviceLagSeconds')
    expect(main).toContain('coverageSloMet')
    expect(main).toContain('Orphans / ambiguity')
    expect(main).toContain('Export · queued / running / oldest')
    expect(main).toContain('projection/requeue-failed')
    expect(main).toContain('Requeue failed')
    expect(main).toContain('max event tip lag')
    expect(main).toContain('openHourStatus')
    expect(main).toContain('open-hour')
  })

  it('wires CDR ingest banner to the real ingest-files API', () => {
    expect(main).toContain('/ingest-files?limit=20')
    expect(main).toContain('CdrIngestBannerLoader')
    expect(main).toContain('CdrIngestBanner')
    expect(main).toContain('SatelPipelineNotice')
  })

  it('keeps EventRow aligned with syslog_messages API', () => {
    expect(main).toContain('payloadSha256: string')
    expect(main).toContain('truncated?: boolean')
    expect(main).not.toContain('rawPayload: string')
    expect(main).not.toContain('parseStatus: string')
    expect(main).not.toContain("category: string\n  component: string")
  })

  it('supports syslog Table / Raw view toggle with shared EventDrawer', () => {
    expect(main).toContain("type SyslogViewMode = 'table' | 'raw'")
    expect(main).toContain('syslogViewMode')
    expect(main).toContain('collector:syslog-view')
    expect(main).toContain('function EventsRawLog')
    expect(main).toContain('syslog-raw-log')
    expect(main).toContain('syslog-raw-payload')
    expect(main).not.toContain('syslog-raw-time')
    expect(main).toContain('view-toggle')
    expect(main).toContain('function EventDrawer')
    expect(main).toContain('onSelect={setSelectedEvent}')
  })

  it('uses Syslog find jump without filtering the day feed', () => {
    expect(main).toContain('function highlightFind')
    expect(main).toContain('syslogFind')
    expect(main).toContain('syslogCommittedFind')
    expect(main).toContain('submitSyslogFind')
    expect(main).toContain('syslog-find-submit')
    expect(main).toContain('syslogHideStream')
    expect(main).toContain('Скрывать поток')
    expect(main).toContain('collector:syslog-hide-stream')
    expect(main).toContain('syslog-find-hit')
    expect(main).toContain('syslog-find-clear')
    expect(main).toContain('syslog-find-prev')
    expect(main).toContain('goSyslogFindPrev')
    expect(main).toContain('goSyslogFindAtIndex')
    expect(main).toContain('centerSyslogHit')
    expect(main).toContain('feedEpochRef')
    expect(main).toContain('syslogMatchItemsRef')
    expect(main).toContain('find-matches')
    expect(main).toContain('syslogFindBusyRef')
    expect(main).toContain("!syslogFindBusyRef.current")
    expect(main).toContain('Найти за сутки')
    expect(main).toContain('/syslog-messages?date=')
    expect(main).toContain('/syslog-messages/find-matches?')
    expect(main).toContain('/syslog-messages/find-count?')
    expect(main).toContain('oldest=1')
    expect(main).toContain('jumpSyslogToHit')
    expect(main).toContain('timeoutMs: 35000')
    expect(main).toContain('ensureSyslogHitInFilteredFeed')
    expect(main).toContain('from_id=')
    expect(main).toContain('loadNewer')
    expect(main).toContain('epoch !== feedEpochRef.current')
    expect(main).toContain('Centering is best-effort')
    expect(main).toContain('Nearby window often has the same call')
    expect(main).not.toContain('ensureSyslogEventVisible')
    expect(main).not.toContain("behavior: 'smooth'")
    expect(main).toContain("syslogHideStream ? syslogCommittedFind : ''")
    expect(main).toContain('&q=${encodeURIComponent(syslogListQ)}')
    expect(main).toContain('Поиск не уложился во время')
    expect(main).toContain('Не удалось открыть совпадение в ленте')
  })

  it('hides antifraud tab when antifraudEnabled is false', () => {
    const template = fallbackTemplates[0]
    expect(deviceSurfaces({ ...template, antifraudEnabled: false }))
      .toEqual(['calls', 'syslog'])
    expect(deviceSurfaces({ ...template, antifraudEnabled: true }))
      .toEqual(['calls', 'syslog', 'antifraud'])
    expect(main).toContain('deviceSurfaces(device)')
  })

  it('does not expose antifraudMode or vendor mode selectors', () => {
    expect(main).not.toContain('antifraudMode')
    expect(main).not.toContain('Astarta')
    expect(main).not.toContain('Intek')
    expect(main).toContain('antifraudEnabled')
    expect(main).toContain('Используется АнтиФрод')
  })

  it('keeps CallDrawer and AntifraudDrawer as coverage dialogue only', () => {
    expect(main).toContain('function CallDrawer')
    expect(main).toContain('function AntifraudDrawer')
    expect(main).toContain('SharedCallCard')
    expect(main).toContain('Покрытие AntiFraud')
    expect(main).toContain('Цепочка AntiFraud')
    expect(main).toContain('AntiFraud JSON')
    expect(main).toContain('antifraudTranscript')
    expect(main).toContain('formatAntifraudTranscript')
    expect(main).toContain('drawer-header')
    expect(main).not.toContain('Пакеты и атрибуты')
  })
})
